---

- name: Deploy the RPS Deployment System for the current user account
  hosts: localhost
  vars:
    deploy_systemd_units_scope: user
    deploy_instance_scope: user
  roles:
    - deploy_deploy
