---

ansible_play_collections_path: collections

ansible_play_install_ansible_galaxy_requirements: true

ansible_play_init_playbook:
  - name: Initialize ansible play environment
    hosts: localhost
    gather_facts: false
    vars:
      install_ansible_galaxy_requirements: "{{ ansible_play_install_ansible_galaxy_requirements }}"
    tasks:
      - name: Get ansible git repo
        git:
          repo: "{{ ansible_play_git_repo }}"
          dest: repo
      - name: Install ansible galaxy requirements
        community.general.ansible_galaxy_install:
          type: both
          requirements_file: repo/requirements.yml
        when: install_ansible_galaxy_requirements

ansible_play_deploy_playbook:
  - import_playbook: "repo/{{ ansible_play_import_playbook_filename }}"
