---

- name: Systemd user config directory
  file:
    path: ~/.config/systemd/user
    state: directory
  when: deploy_systemd_units_scope == "user"

- name: Template systemd {{ deploy_systemd_units_scope }} unit files
  template:
    src: "{{ item.src }}"
    dest: "{{ deploy_systemd_units_unit_path }}/{{ item.path | regex_replace('\\.j2$', '') }}"
  with_filetree: "{{ role_path }}/templates/systemd"
  loop_control:
    label: "{{ item.path | regex_replace('\\.j2$', '') }}"
  notify: Reload systemd {{ deploy_systemd_units_scope }} daemon

- name: Flush all handlers after unit file copying is finished
  meta: flush_handlers
