---

- name: Copy static systemd unit files
  copy:
    src: systemd/
    dest: "{{ deploy_systemd_units_unit_path }}"
  notify: Reload systemd {{ deploy_systemd_units_scope }} daemon

- name: Flush all handlers after unit file copying is finished
  meta: flush_handlers
